language: python
services:
  - postgresql
addons:
  postgresql: "9.2"
python:
  - "2.7"
  - "3.6"
install:
  - pip install -r requirements.txt
  - pip install flake8
  - if [[ $TRAVIS_PYTHON_VERSION != 2.7 ]]; then pip install mypy; fi
script:
  - if [[ $TRAVIS_PYTHON_VERSION = 2.7 ]]; then flake8; fi
  - if [[ $TRAVIS_PYTHON_VERSION != 2.7 ]]; then mypy flask_phpbb3.py; fi
  - if [[ $TRAVIS_PYTHON_VERSION = 2.7 ]]; then python setup.py test; fi
